autoload -U select-word-style
select-word-style bash

source ~/.config/zsh/secrets.zsh
source ~/.config/zsh/colors.zsh
source ~/.config/zsh/setopt.zsh
source ~/.config/zsh/exports.zsh
source ~/.config/zsh/prompt.zsh
source ~/.config/zsh/completion.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/functions.zsh
source ~/.config/zsh/bindkeys.zsh
source ~/.config/zsh/history.zsh
source ~/.config/zsh/zsh_hooks.zsh
source "${HOME}/.bin/zgen/zgen.zsh"

if which rbenv > /dev/null; then
  eval "$(rbenv init -)"
fi

function npm_chpwd_hook() {
  NPMPATH="$(npm bin)"

  if [ -d "$NPMPATH" ]; then
    PATH=$PRENPMPATH:$NPMPATH
  else
    PATH=$PRENPMPATH
  fi

  export PATH=$PATH
}

export PRENPMPATH=$PATH
# npm_chpwd_hook

if ! zgen saved; then
  echo "Creating Zgen stuff"
  zgen load uvaes/fzf-marks
  zgen load zsh-users/zsh-syntax-highlighting

  zgen save

fi

# source /usr/local/bin/virtualenvwrapper.sh
